[theme]
base = "light"
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F8"
textColor = "#171717"
font = "sans serif"

[server]
maxUploadSize = 25

[browser]
gatherUsageStats = false
